apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: local-path-storage
    server: https://192.168.0.14:6443
  source:
    repoURL: "https://github.com/maor-klir/homelab-k8s-cluster-2.git"
    targetRevision: main
    path: infrastructure/controllers/staging/local-path-provisioner
  project: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
