apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sealed-secrets
    server: https://192.168.0.14:6443
  source:
    repoURL: "https://github.com/maor-klir/homelab-k8s-cluster-2.git"
    targetRevision: main
    path: infrastructure/core/staging/sealed-secrets
  project: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
