apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../test/cilium

patches:
  - target:
      name: lb-pool
      kind: CiliumLoadBalancerIPPool
    patch: |-
      - op: replace
        path: /spec/blocks/start
        value: "192.168.0.211"
      - op: replace
        path: /spec/blocks/stop
        value: "192.168.0.220"
