apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../test/cilium

patches:
  - target:
      name: lb-pool
      kind: CiliumLoadBalancerIPPool
    patch: |-
      - op: replace
        path: /spec/blocks/0
        value:
          start: "192.168.0.211"
          stop: "192.168.0.220"
