apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudflare-api-token.yaml
  - namespace.yaml

helmCharts:
  - name: external-dns
    releaseName: external-dns
    version: 1.16.1
    repo: https://kubernetes-sigs.github.io/external-dns/
    namespace: external-dns
    valuesFile: values.yaml
