env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token
provider:
  name: cloudflare
sources:
  - service
  - ingress
  - gateway-httproute
  - gateway-tlsroute
  - gateway-grpcroute
  - gateway-udproute
  - gateway-tcproute
