apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key # The Kubernetes Secret that will get created (in the "external-secrets" namespace)
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: talos-external-dns-cf-token # The name of the secret in AWS Secrets Manager
