apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cloudflare-token.yaml

helmCharts:
  - name: external-dns
    releaseName: external-dns
    version: 8.7.7
    repo: oci://registry-1.docker.io/bitnamicharts/external-dns
    namespace: external-dns
    valuesFile: values.yaml
