apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cloudflare-token.yaml

helmCharts:
  - name: external-dns
    releaseName: bitnami/external-dns
    version: 8.7.7
    repo: https://charts.bitnami.com/bitnami
    namespace: external-dns
    valuesFile: values.yaml
