provider: cloudflare
# env:
#   - name: CF_API_TOKEN
#     valueFrom:
#       secretKeyRef:
#         name: cloudflare-api-token
#         key: api-token

cloudflare:
  apiToken: CF_API_TOKEN
  secretName: cloudflare-api-token

sources:
  - service
  - ingress
  - gateway-httproute
  - gateway-tlsroute
  - gateway-grpcroute
  - gateway-udproute
  - gateway-tcproute
