# This option is equivalent to setting crds.enabled=true and crds.keep=true.
# Deprecated: use crds.enabled and crds.keep instead.
# installCRDs: false
crds:
  # This option decides if the CRDs should be installed
  # as part of the Helm installation.
  enabled: true
  # This option makes it so that the "helm.sh/resource-policy": keep
  # annotation is added to the CRD. This will prevent Helm from uninstalling
  # the CRD when the Helm release is uninstalled.
  # WARNING: when the CRDs are removed, all cert-manager custom resources
  # (Certificates, Issuers, ...) will be removed too by the garbage collector.
  keep: true

# Setting Nameservers for DNS01 Self Check.
# For more information, see:
# [cert-manager documentation](https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check).
dns01RecursiveNameservers: 8.8.8.8:53\,1.1.1.1:53
dns01RecursiveNameserversOnly: true