apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: alloy
    releaseName: alloy
    version: 1.0.0
    repo: https://prometheus-community.github.io/helm-charts
    namespace: observability
    valuesFile: values.yaml
