apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana
    releaseName: grafana
    version: 8.13.0
    repo: https://prometheus-community.github.io/helm-charts
    namespace: observability
    valuesFile: values.yaml
