apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: argocd-tls-upstream
spec:
  targetRefs:
    - kind: Service
      name: argocd-server
      group: ""
  validation:
    CACertificateRefs: argocd-certificate
    hostname: argocd.cloudandklir.com