apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  # annotations:
  #   # Add an annotation indicating the issuer to use.
  #   cert-manager.io/cluster-issuer: acme-staging
  #   # In order to expose the Argo CD API server with a single ingress rule and hostname, 
  #   # this annotation must be used to passthrough TLS connections and terminate TLS at the Argo CD API server.
  #   ingress.cilium.io/tls-passthrough: enabled
spec:
  ingressClassName: cilium
  rules:
  - host: argocd.cloudandklir.com
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 80
        path: /
        pathType: Prefix
  # tls:
  # - hosts:
  #     - argocd.cloudandklir.com
  #   secretName: argocd-server-tls # As expected by argocd-server