apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yaml
# - certificate.yaml

helmCharts:
  - name: argo-cd
    releaseName: argocd
    version: 7.8.10
    repo: https://argoproj.github.io/argo-helm
    namespace: argocd
    valuesFile: values.yaml