apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - backend-tls-policy.yaml
  - certificate.yaml
  - gateway.yaml
  - tls-route.yaml

helmCharts:
  - name: argo-cd
    releaseName: argocd
    version: 7.8.14
    repo: https://argoproj.github.io/argo-helm
    namespace: argocd
    valuesFile: values.yaml