configs:
  cm:
    kustomize.buildOptions: "--enable-helm --load-restrictor=LoadRestrictionsNone"

crds:
  install: true
  # -- Keep CRDs on chart uninstall
  keep: false

server:
  ingress:
    enabled: true
    controller: generic
    ingressClassName: cilium
    hostname: argocd.cloudandklir.com
    path: /
    pathType: Prefix
    tls: false
