configs:
  cm:
    kustomize.buildOptions: "--enable-helm --load-restrictor=LoadRestrictionsNone"
  # params:
  #   server.insecure: "true"  

crds:
  install: true
  # -- Keep CRDs on chart uninstall
  keep: false