configs:
  cm:
    kustomize.buildOptions: "--enable-helm --load-restrictor=LoadRestrictionsNone"

crds:
  install: true
  # -- Keep CRDs on chart uninstall
  keep: false

server:
  # ingress:
  #   enabled: true
  #   controller: generic
  #   ingressClassName: cilium
  #   annoatations:
  #     ingress.cilium.io/tls-passthrough: true
  #     cert-manager.io/cluster-issuer: acme-staging
  #   hostname: argocd.cloudandklir.com
  #   path: /
  #   pathType: Prefix
  #   tls: true
  certificate:
    enabled: true
    domain: cloudandklir.com
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: acme-staging
  certificateSecret:
    enabled: true
    key: tls.key
    crt: tls.crt
