apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: tempo
    releaseName: tempo
    version: 1.20.0
    repo: https://grafana.github.io/helm-charts
    namespace: observability
    valuesFile: values.yaml
