apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allowed-hosts-cm.yaml
  - configmap.yaml
  - deployment.yaml
  - gateway.yaml
  - namespace.yaml
  - rbac.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - tls-certificate.yaml
  - tls-route.yaml
