apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- allowed-hosts-cm.yaml
- cm.yaml
- cr-crb.yaml
- deploy,.yaml
- ingress.yaml
- ns.yaml
- sa.yaml
- secret.yaml
- svc.yaml
- tls-cert.yaml