apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls-certificate
  namespace: homepage
spec:
  secretName: homepage-tls
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
  dnsNames:
    - homepage.cloudandklir.com
