apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealed-secret.yaml

helmCharts:
  - name: pi-hole
    releaseName: pi-hole
    version: 2.29.0
    repo: https://mojo2600.github.io/pihole-kubernetes/
    namespace: pi-hole
    valuesFile: values.yaml