---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-hole-secret
  namespace: pi-hole
spec:
  encryptedData:
    password: AgC8oxlIHoidxrf3Ke/tZJUEKp6zB8M0q22aJplRPh026SzB8QWs/o2rOOgAt1Uh3f9eRp3FEWzj3j4XCzEb0l9wWK++sxScCtsEQlQYenl+iEPYuc6sFAE0sdfh/D4VtNE3DDZl6nxV7GWDbvFUOU23Y0ogBS1hZE09RtZadAepYw/+CPC4hkbD4I+bIWVsFM8VpLKBEqRFrzPHlQCgg0jEp4Bi9SGeUKTTQAEkBG6nkP771JIwgaj9YzUtICCCuG4nnhLIU/3lSbK23vVSWC8gED4a2AHU8qOCNn4JzMJoxPcL9CpvfDOJCVaMMPvLI3yTTi8ROOcVg4tdEyN3h6behWPnhRRTtJlpuDGE2O3vGXpaF8w/VIqDDSlSdaIgjF5zHKNbjTuRzJfoNlxa1HHVJ9LBDohM+kcKv+uNGqlFzq10Z64b7P8ikzpP1f1RI5uOT8RfCecddsGUYHSgo2nQMJe/dCvkMDmOH217Mliu5JjLxODQGbxkmTljpy271NTLqtutajhpW8ID4C0USxXCyE3UxFxcJhz2qYN3efeORXDefLfjhx94JlyVVOpqFZUO7hqI9wqQ/RPbM4MeFOKd0uYsL7DfGBZ++c9Kv9W/tIiv86iTwLLtbPx3T1t6IXNL6gHtPKqpZzRwLx6i/dyHN1OQHAl5oxJGse/0Dq+naTkdxkiQxcfaGvOv602ANiFDtcJQtLTx8g==
  template:
    metadata:
      name: pi-hole-secret
      namespace: pi-hole