apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pi-hole-tls-certificate
  namespace: pi-hole
spec:
  secretName: pi-hole-tls
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
  dnsNames:
    - pi-hole.cloudandklir.com
