---
# replicaCount: 2
# maxUnavailable: 1

serviceDns:
  mixedService: true
  loadBalancerIP: 192.168.0.203
  type: LoadBalancer

serviceDhcp:
  enabled: false

resources: 
  limits:
   cpu: 500m
   memory: 512Mi
  requests:
   cpu: 100m
   memory: 256Mi

persistentVolumeClaim:
  enabled: true
  storageClass: local-path
  size: "1Gi"

admin:
  enabled: true
  existingSecret: "pi-hole-secret"
  passwordKey: "password"

extraEnvVars:
  TZ: "Europe/Berlin"
  FTLCONF_dns_listeningMode: "all"

extraEnvVarsSecret:
  PIHOLE_PASSWORD:
    name: pi-hole-secret
    key: password

DNS1: "1.1.1.1"
DNS2: "1.0.0.1"

adlists:
  # Core and widely recommended lists
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  # - https://oisd.nl/basic
  - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/multi.txt
  - https://adaway.org/hosts.txt

  # Firebog curated lists (removes some redundancy by using Firebog's versions)
  - https://v.firebog.net/hosts/Easylist.txt
  - https://v.firebog.net/hosts/Easyprivacy.txt
  - https://v.firebog.net/hosts/AdguardDNS.txt # Included for completeness, but functionally similar to direct AdGuard list
  - https://v.firebog.net/hosts/static/w3kbl.txt # WaLLy3K's list

  # Specific focus lists
  - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt # Fraud, Scam, Phishing
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts # Spam
  - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt # Anti-Malware
  - https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt # Scam
  # - https://raw.githubusercontent.com/mitchellkrogza/The-Big-List_of_Hacked-Malware-Web-Sites/master/hosts # Hacked Malware
  - https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt # Malware based on URLhaus
  - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt # Extended Ads and Tracking
  - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt # Windows Telemetry
  - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt # First-party trackers
  - https://v.firebog.net/hosts/Prigent-Crypto.txt # Crypto
  - https://phishing.army/download/phishing_army_blocklist_extended.txt # Phishing Army Extended
  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt # Quidsup NoTrack Malware
  - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt # Spam404
  - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts # Stalkerware
  - https://lists.cyberhost.uk/malware.txt # Cyberhost UK Malware

# podDnsConfig:
#   enabled: true
#   policy: "None"
#   nameservers:
#   - 127.0.0.1
#   - 1.1.1.1

# capabilities:
#   add:
#     - CAP_SYS_NICE

probes:
  liveness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 5
    port: http 
    scheme: HTTP
  readiness:
    enabled: true
    initialDelaySeconds: 60 
    failureThreshold: 10 
    timeoutSeconds: 5 
    port: http 
    scheme: HTTP