# As per Talos Linux documentation - https://www.talos.dev/v1.9/kubernetes-guides/configuration/local-storage/#local-path-provisioner

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rancher/local-path-provisioner/deploy?ref=v0.0.31