apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
  namespace: kube-system
spec:
  # serviceSelector:
  #   matchLabels:
  #     cilium-lb-pool: lb-pool
  loadBalancerIPs: true
  # Optional - externalIPs: true
  # The externalIPs.enabled=true Helm option must be set, if usage of externalIPs is desired. 
  # Otherwise service load balancing for external IPs is disabled.
  # https://kubernetes.io/docs/concepts/services-networking/service/#external-ips