apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.0.201"
      stop: "192.168.0.210"
  serviceSelector:
    matchLabels:
      cilium-lb-pool: lb-pool