apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: mimir
    releaseName: mimir
    version: 5.6.0
    repo: https://grafana.github.io/helm-charts
    namespace: observability
    valuesFile: values.yaml
