apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: loki
    releaseName: loki
    version: 6.28.0
    repo: https://grafana.github.io/helm-charts
    namespace: observability
    valuesFile: values.yaml
