---
loki:
  # Use monolithic mode for simplicity on a small cluster with local storage
  target: monolithic
  auth_enabled: false # Often useful to disable auth for testing

  # === ADDED TO SATISFY HELM TEMPLATE ===
  # The template seems to expect this structure even in filesystem mode.
  # Add dummy values here.
  storage:
    bucketNames:
      chunks: dummy-chunks-bucket
      ruler: dummy-ruler-bucket
      admin: dummy-admin-bucket
      # Add other bucket names if the template references them (less common)

    # Add dummy object store config required by some templates
    s3: # Or gcs, azure, etc., depending on what the template expects
      endpoint: dummy
      bucket_name: dummy-bucket
      access_key_id: dummy
      secret_access_key: dummy
      insecure: true # Set true if using dummy endpoint
  # =====================================

  structuredConfig:
    common:
      storage:
        # Filesystem backend for monolithic mode with local storage
        backend: filesystem
        filesystem:
          dir: /data/loki
    # Configure the boltdb-shipper index and chunks storage within the filesystem backend
    ingester:
      chunk_idle_period: 5m
      chunk_retain_period: 30s
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: filesystem
      compaction_interval: 10m
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        resync_interval: 5m
        shared_store: filesystem # Use filesystem for shared store in monolithic mode
    ruler:
      storage:
        type: local
        local:
          directory: /data/loki/ruler
    # Add query_range and other structuredConfig sections as needed from the previous plan
    query_range:
      align_queries_with_step: true

# Configure statefulset and PVC for the monolithic instance
statefulset:
  enabled: true
  replicas: 1 # Set to 1 due to local storage constraints with local-path
  volumeMounts:
    - name: storage
      mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path # Specify the local-path storage class
        resources:
          requests:
            storage: 50Gi # Adjust size as needed based on expected log volume

# Disable other components not needed in monolithic mode deployment via Helm
backend:
  enabled: false
read:
  enabled: false
write:
  enabled: false
