apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    version: 2.17.2
    repo: https://bitnami-labs.github.io/sealed-secrets
    namespace: sealed-secrets
    includeCRDs: true
